# Generated by Django 5.2.3 on 2025-07-01 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('add_date', models.DateField(verbose_name='date added')),
                ('checked_out', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('catalogitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.catalogitem')),
                ('author', models.CharField(max_length=100)),
            ],
            bases=('api.catalogitem',),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('catalogitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.catalogitem')),
                ('developer', models.CharField(max_length=100)),
            ],
            bases=('api.catalogitem',),
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('catalogitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.catalogitem')),
                ('issue', models.IntegerField(default=1)),
            ],
            bases=('api.catalogitem',),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('catalogitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.catalogitem')),
                ('director', models.CharField(max_length=100)),
            ],
            bases=('api.catalogitem',),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='user',
            field=models.ManyToManyField(blank=True, to='api.user'),
        ),
    ]
